package com.example.monk_prj.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;

import java.net.http.HttpResponse;

@Slf4j
@Getter
@AllArgsConstructor
public enum ErrorTypes {
    INVALID_REQUEST_BODY("INVALID_REQUEST_BODY", HttpStatus.BAD_REQUEST),
    INVALID_CART("INVALID_CART", HttpStatus.BAD_REQUEST),
    EMPTY_CART("EMPTY_CART", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT("INVALID_PRODUCT", HttpStatus.BAD_REQUEST),
    BLANK_PRODUCT_NAME("BLANK_PRODUCT_NAME", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_CATEGORY("INVALID_PRODUCT_CATEGORY", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_ID("INVALID_PRODUCT_ID", HttpStatus.BAD_REQUEST),
    INVALID_PRICE("INVALID_PRICE", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_ORDER("INVALID_PRODUCT_ORDER", HttpStatus.BAD_REQUEST),
    INVALID_ORDER_QUANTITY("INVALID_ORDER_QUANTITY", HttpStatus.BAD_REQUEST),
    INVALID_BUY_PRODUCT_CATEGORY("INVALID_BUY_PRODUCT_CATEGORY", HttpStatus.BAD_REQUEST),
    INVALID_GET_PRODUCT_CATEGORY("INVALID_GET_PRODUCT_CATEGORY", HttpStatus.BAD_REQUEST),
    INVALID_BUY_PRODUCT_IDS("INVALID_BUY_PRODUCT_IDS", HttpStatus.BAD_REQUEST),
    INVALID_GET_PRODUCT_IDS("INVALID_GET_PRODUCT_IDS", HttpStatus.BAD_REQUEST),
    INVALID_THRESHOLD_AMOUNT("INVALID_THRESHOLD_AMOUNT", HttpStatus.BAD_REQUEST),
    INVALID_X_AMOUNT("INVALID_X_AMOUNT", HttpStatus.BAD_REQUEST),
    INVALID_Y_AMOUNT("INVALID_Y_AMOUNT", HttpStatus.BAD_REQUEST),
    INVALID_REPETITION_LIMIT("INVALID_REPETITION_LIMIT", HttpStatus.BAD_REQUEST),
    INVALID_DISCOUNT_PERCENT("INVALID_DISCOUNT_PERCENT", HttpStatus.BAD_REQUEST),
    INVALID_COUPON_DETAILS("INVALID_COUPON_DETAILS", HttpStatus.BAD_REQUEST),
    INVALID_COUPON_TYPE("INVALID_COUPON_TYPE", HttpStatus.BAD_REQUEST),
    INVALID_COUPON("INVALID_COUPON", HttpStatus.BAD_REQUEST),
    INVALID_ID("INVALID_ID", HttpStatus.BAD_REQUEST);

    private final String name;
    private final HttpStatus httpStatus;
}
